version: "3.3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - .:/athenas_lab
    ports:
      - "80:80"
    env_file:
      - .env
    tty: true
    networks:
      - athenas_lab

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/athenas_lab
    env_file:
      - .env
    networks:
      - athenas_lab
volumes:
  redis:
  postgres:
networks:
  athenas_lab:
    external: true
