version: "3.3"
services:
  telegram:
    build: .
    command: bash -c "exe/chatgpt_bot telegram"
    volumes:
      - .:/chatgpt_assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    networks:
      - athenas_lab
  discord:
    build: .
    command: bash -c "exe/chatgpt_bot discord"
    volumes:
      - .:/chatgpt_assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    networks:
      - athenas_lab
  redis:
    image: redis:6-alpine
    ports:
      - "6380:6380"
    volumes:
      - ./redis_data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq -C ./lib/chatgpt_assistant/sidekiq.yml -r ./lib/chatgpt_assistant/sidekiq.rb -q ruby_queue
    volumes:
      - .:/chatgpt_assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - athenas_lab

volumes:
  postgres:
  redis:
networks:
  athenas_lab:
    external: true