version: "3.3"
services:
  telegram:
    build: .
    command: bash -c "exe/chatgpt_bot telegram"
    volumes:
      - .:/athenas_ai
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    networks:
      - athenas_lab

  discord:
    build: .
    command: bash -c "exe/chatgpt_bot discord"
    volumes:
      - .:/athenas_ai
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    networks:
      - athenas_lab
volumes:
  postgres:
networks:
  athenas_lab:
    external: true